services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test # MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: test # MongoDB root password
    ports:
      - "27017:27017" # Expose port 27017
    volumes:
      - ./tmp/db:/data/db # Volume for data persistence
